import React from 'react';

export const metadata = {
  title: 'CodeKino Dashboard',
  description: 'Generated by CodeKino',
};

export default function Page() {
  return (
    <>

{/*  Main Navigation (TopNavBar)  */}
<nav className="fixed top-0 left-0 right-0 z-50 bg-zinc-900/70 backdrop-blur-3xl shadow-2xl shadow-black/50 flex justify-between items-center px-8 h-14">
<div className="text-lg font-bold tracking-tighter text-zinc-100">CodeKino</div>
<div className="hidden md:flex gap-8 items-center">
<a className="font-inter tracking-tight text-sm font-medium text-blue-400 font-semibold hover:text-white transition-colors duration-200" href="#">Platform</a>
<a className="font-inter tracking-tight text-sm font-medium text-zinc-400 hover:text-white transition-colors duration-200" href="#">Features</a>
<a className="font-inter tracking-tight text-sm font-medium text-zinc-400 hover:text-white transition-colors duration-200" href="#">Complexity</a>
<a className="font-inter tracking-tight text-sm font-medium text-zinc-400 hover:text-white transition-colors duration-200" href="#">Transcript</a>
</div>
<div className="flex items-center gap-4">
<button className="px-4 py-1.5 bg-primary text-on-primary rounded-full text-sm font-medium scale-95 active:opacity-80 transition-all">Get Started</button>
</div>
</nav>

{/*  Page body: padded for fixed nav + footer, centered  */}
<div className="min-h-screen pt-14 pb-20 flex items-center justify-center px-4 bg-zinc-950">

{/*  Main Application Wrapper (macOS Window)  */}
<main className="w-full max-w-6xl bg-surface-container-low rounded-xl mac-shadow overflow-hidden flex flex-col" style={{minHeight: '600px', height: 'calc(100vh - 14rem)'}}>
{/*  Window Title Bar  */}
<div className="h-10 shrink-0 flex items-center px-4 bg-surface-container-high/30 border-b border-white/5 backdrop-blur-md">
<div className="flex gap-2">
<div className="w-3.5 h-3.5 rounded-full bg-[#FF5F57] shadow-inner"></div>
<div className="w-3.5 h-3.5 rounded-full bg-[#FEBC2E] shadow-inner"></div>
<div className="w-3.5 h-3.5 rounded-full bg-[#28C840] shadow-inner"></div>
</div>
<div className="flex-1 text-center text-xs font-medium text-zinc-500 tracking-wide select-none">
  dashboard.codekino — python-analyzer
</div>
</div>
<div className="flex flex-1 overflow-hidden min-h-0">
{/*  Left Pane: Input (Dropzone)  */}
<section className="flex-1 p-8 flex flex-col gap-6 bg-surface-container-lowest overflow-y-auto">
<div className="flex flex-col gap-1">
<h1 className="text-2xl font-semibold tracking-tight text-white">Input Source</h1>
<p className="text-sm text-zinc-500">Provide the Python script to generate visualization.</p>
</div>
<div className="flex-1 rounded-xl border border-dashed border-outline-variant/30 bg-surface-container-highest/20 flex flex-col items-center justify-center gap-4 group cursor-pointer hover:bg-surface-container-highest/40 transition-all duration-300 backdrop-blur-sm min-h-40">
<div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center text-primary group-hover:scale-110 transition-transform duration-300">
<span className="material-symbols-outlined text-4xl" data-weight="fill">description</span>
</div>
<div className="text-center">
<p className="text-lg font-medium text-zinc-200">Drag your .py script here.</p>
<p className="text-xs text-zinc-500 mt-1">Or click to browse from system files</p>
</div>
</div>
<div className="shrink-0 h-32 rounded-lg bg-surface-container-high/40 p-4 border border-white/5 overflow-hidden">
<div className="flex justify-between items-center mb-3">
<span className="text-[10px] uppercase tracking-widest font-bold text-zinc-500">Processing Status</span>
<span className="text-[10px] text-blue-400 font-mono animate-pulse">Parsing AST logic...</span>
</div>
<div className="w-full h-1 bg-zinc-800 rounded-full overflow-hidden">
<div className="h-full bg-primary w-[65%] rounded-full transition-all duration-1000 shadow-[0_0_8px_rgba(170,199,255,0.4)]"></div>
</div>
<div className="mt-4 flex gap-4 text-[11px] font-mono text-zinc-500">
<div className="flex flex-col">
<span className="text-zinc-400">Tokens</span>
<span>4,291</span>
</div>
<div className="flex flex-col">
<span className="text-zinc-400">Nodes</span>
<span>128</span>
</div>
<div className="flex flex-col">
<span className="text-zinc-400">Depth</span>
<span>12</span>
</div>
</div>
</div>
</section>
{/*  Middle Pane: Generation/Output (Video Player)  */}
<section className="flex-[1.5] bg-surface border-x border-white/5 p-6 flex flex-col gap-4 relative overflow-hidden">
<div className="flex justify-between items-center shrink-0">
<div className="flex items-center gap-2">
<div className="w-2 h-2 rounded-full bg-secondary"></div>
<h2 className="text-sm font-semibold text-zinc-300">Live Preview</h2>
</div>
<div className="flex gap-2">
<button className="p-1.5 hover:bg-zinc-800 rounded-md text-zinc-500 hover:text-white transition-colors">
<span className="material-symbols-outlined text-sm">download</span>
</button>
<button className="p-1.5 hover:bg-zinc-800 rounded-md text-zinc-500 hover:text-white transition-colors">
<span className="material-symbols-outlined text-sm">share</span>
</button>
</div>
</div>
{/*  Video Player Container  */}
<div className="flex-1 rounded-xl overflow-hidden bg-black mac-shadow group relative min-h-0">
<img alt="Cinematic code visualization" className="w-full h-full object-cover opacity-60 group-hover:opacity-40 transition-opacity duration-500" data-alt="Abstract cinematic visualization of computer code flowing through digital obsidian space with glowing blue and purple light trails" src="https://lh3.googleusercontent.com/aida-public/AB6AXuAYdq6ThBf-WWxok-UrC81zINHwnGA9_8hvM2gj6zG66cODdmL3VUJarYOJUVGwjFP64EPWqKAfNsEZrUyaQYt4542tfUJ3q1zEjs4RA_fcIlJgqpotymUYws8-xqCU9Vm0E1mtL9Mh2HcEXogtVHTf6H1KdBzx9JGD6c0UPrS0c7umoCeON39EEiTr1Yau3mH2-pQFLx-AgOjjeixJkIY4322L_SHOBLldkjtbTI8ybfBQab0YcntlmHtKfZb2kSV3zHZ8uFfVPJ38" />
{/*  QuickTime Style Overlay  */}
<div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
<button className="w-16 h-16 rounded-full bg-white/10 backdrop-blur-xl flex items-center justify-center text-white hover:scale-105 active:scale-95 transition-all">
<span className="material-symbols-outlined text-4xl" data-weight="fill">play_arrow</span>
</button>
</div>
{/*  Scrubber Bar  */}
<div className="absolute bottom-0 left-0 right-0 p-4 translate-y-full group-hover:translate-y-0 transition-transform duration-300 bg-gradient-to-t from-black/80 to-transparent">
<div className="flex items-center gap-4">
<span className="text-[10px] font-mono text-white/70">00:42</span>
<div className="flex-1 h-1 bg-white/20 rounded-full relative group/scrub cursor-pointer">
<div className="absolute inset-y-0 left-0 bg-primary w-[45%] rounded-full"></div>
<div className="absolute left-[45%] top-1/2 -translate-y-1/2 w-3 h-3 bg-white rounded-full shadow-lg scale-0 group-hover/scrub:scale-100 transition-transform"></div>
</div>
<span className="text-[10px] font-mono text-white/70">01:15</span>
</div>
</div>
</div>
{/*  Bento Info Cards  */}
<div className="grid grid-cols-2 gap-4 shrink-0 h-32">
<div className="bg-surface-container-high/50 rounded-xl p-4 border border-white/5 backdrop-blur-sm flex flex-col justify-between">
<span className="text-[10px] uppercase tracking-wider font-bold text-zinc-500">Resolution</span>
<span className="text-xl font-headline font-semibold text-white">4K Editorial</span>
</div>
<div className="bg-surface-container-high/50 rounded-xl p-4 border border-white/5 backdrop-blur-sm flex flex-col justify-between">
<span className="text-[10px] uppercase tracking-wider font-bold text-zinc-500">Render Time</span>
<span className="text-xl font-headline font-semibold text-white">~ 2.4s</span>
</div>
</div>
</section>
{/*  Sidebar (Right-aligned): Widgets & Transcript  */}
<aside className="w-72 shrink-0 bg-zinc-900/50 backdrop-blur-2xl border-l border-white/5 flex flex-col overflow-hidden">
<div className="p-6 border-b border-white/5 shrink-0">
<div className="flex items-center gap-3 mb-6">
<div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-secondary p-[1px] shrink-0">
<img alt="User Profile" className="w-full h-full rounded-full object-cover" data-alt="Professional studio portrait of a software engineer with minimalist aesthetic" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDI7OrEdFU9BllOQh1fXJmOgTpY7TOE2Fzo3jsB9bq_2w98Ake9rIPEgECVnoZL9YX73OTJKzj64QjbVuw1GXa-PWNHrAmgZaXMu2qpwUZgkNp2mXBFx3QqOuztCktWNIXtTuDpUujiANnkLbkLlSxGegdwLitcpyQVbd0ieoyQUWUt-EVA3eTCdtwZx-DFrOHkVBE7ZIoHDhpSVHQjdZ8X5LBEfIozCqMhNvhVQHGPQbaBIz-GpFi0roRzMunXzQNtR48z7K-BEpbQ" />
</div>
<div>
<p className="text-xs font-bold text-white uppercase tracking-widest">CodeKino Pro</p>
<p className="text-[10px] text-blue-400/80 font-medium">Premium Tier</p>
</div>
</div>
{/*  Widgets  */}
<div className="space-y-4">
<div className="bg-surface-container-highest/30 rounded-xl p-4 border border-white/10 backdrop-blur-sm">
<div className="flex items-center justify-between mb-2">
<span className="text-[10px] font-bold uppercase text-zinc-500 tracking-tighter">Time Complexity</span>
<span className="material-symbols-outlined text-blue-400 text-xs">schedule</span>
</div>
<p className="text-lg font-mono font-bold text-white">O(n log n)</p>
<div className="mt-2 h-1 w-full bg-zinc-800 rounded-full">
<div className="h-full bg-blue-400 w-3/4 rounded-full"></div>
</div>
</div>
<div className="bg-surface-container-highest/30 rounded-xl p-4 border border-white/10 backdrop-blur-sm">
<div className="flex items-center justify-between mb-2">
<span className="text-[10px] font-bold uppercase text-zinc-500 tracking-tighter">Space Complexity</span>
<span className="material-symbols-outlined text-secondary text-xs">memory</span>
</div>
<p className="text-lg font-mono font-bold text-white">O(n)</p>
<div className="mt-2 h-1 w-full bg-zinc-800 rounded-full">
<div className="h-full bg-secondary w-1/2 rounded-full"></div>
</div>
</div>
</div>
</div>
{/*  Accordion: Audio Transcript  */}
<div className="flex-1 flex flex-col overflow-hidden min-h-0">
<button className="w-full p-4 shrink-0 flex items-center justify-between text-zinc-300 hover:bg-zinc-800/30 transition-colors">
<div className="flex items-center gap-2">
<span className="material-symbols-outlined text-sm">record_voice_over</span>
<span className="text-xs font-bold uppercase tracking-widest">Audio Transcript</span>
</div>
<span className="material-symbols-outlined text-sm">expand_more</span>
</button>
<div className="flex-1 px-4 pb-4 overflow-y-auto no-scrollbar space-y-4">
<div className="space-y-3">
<div className="p-3 rounded-lg bg-surface-container-low border border-white/5">
<p className="text-[11px] text-zinc-400 leading-relaxed">
<span className="text-primary-fixed-dim font-mono">[00:12]</span> Defining the core recursive function for the Fibonacci sequence with memoization optimization.
</p>
</div>
<div className="p-3 rounded-lg bg-surface-container-low border border-white/5 opacity-50">
<p className="text-[11px] text-zinc-400 leading-relaxed">
<span className="text-primary-fixed-dim font-mono">[00:45]</span> Analyzing tree traversal logic and identifying potential O(n^2) bottlenecks in the nested loop...
</p>
</div>
<div className="p-3 rounded-lg bg-surface-container-low border border-white/5 opacity-30">
<p className="text-[11px] text-zinc-400 leading-relaxed">
<span className="text-primary-fixed-dim font-mono">[01:15]</span> Finalizing visual representation of data structures...
</p>
</div>
</div>
</div>
</div>
{/*  Sidebar Footer  */}
<div className="p-4 shrink-0 bg-surface-container-high/20 border-t border-white/5 flex flex-col gap-2">
<button className="w-full py-2 bg-blue-500/10 text-blue-400 rounded-lg text-[10px] font-bold uppercase tracking-widest hover:bg-blue-500/20 transition-all">Upgrade Plan</button>
<div className="flex justify-between items-center px-2 py-2">
<button className="text-[10px] text-zinc-500 hover:text-zinc-200 transition-colors flex items-center gap-1 uppercase tracking-widest font-bold">
<span className="material-symbols-outlined text-sm">help</span>
Support
</button>
<button className="text-[10px] text-zinc-500 hover:text-zinc-200 transition-colors flex items-center gap-1 uppercase tracking-widest font-bold">
<span className="material-symbols-outlined text-sm">logout</span>
Sign Out
</button>
</div>
</div>
</aside>
</div>
</main>

</div>

{/*  Footer  */}
<footer className="fixed bottom-0 left-0 right-0 py-4 flex flex-col items-center gap-2 border-t border-white/5 bg-zinc-950/80 backdrop-blur-md z-50">
<div className="flex gap-6">
<a className="text-xs text-zinc-600 hover:text-blue-400 transition-opacity duration-300" href="#">Privacy</a>
<a className="text-xs text-zinc-600 hover:text-blue-400 transition-opacity duration-300" href="#">Terms</a>
<a className="text-xs text-zinc-600 hover:text-blue-400 transition-opacity duration-300" href="#">Security</a>
<a className="text-xs text-zinc-600 hover:text-blue-400 transition-opacity duration-300" href="#">Status</a>
</div>
<p className="font-inter text-[10px] text-zinc-500 uppercase tracking-widest">© 2024 CodeKino. Designed for macOS.</p>
</footer>

    </>
  );
}